### PR TITLE
Did some things to westin's world!

### PR DESCRIPTION
**Pull request by mcvellaa**
It's totally legitimate, I promise!

### CODE REVIEW

**Comment by westin** [comment]
I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project

**Comment by westin** [comment]
THIS LOOKS GREAT DUDE!!!!!! i love it :+1:

**Comment by mcvellaa** [comment]
I AM SO GLAD YOU LIKE IT

**Comment by westin** [comment]
wow i love this class!

**Comment by mcvellaa** [comment]
I am honored

**Pull request merged**
